steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyAO3xx6mnITcD9h6GDk7qhzpQMvSiswSVk'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=pantry-pal-66ed8.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=pantry-pal-66ed8'
      - '--build-arg'
      - 'VITE_FIREBASE_FIRESTORE_DATABASE_ID=default'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=pantry-pal-66ed8.firebasestorage.app'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=557285061653'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=1:557285061653:web:d777e9405d61032bab8a1c'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=G-MM184JNZ75'
      - '--build-arg'
      - 'VITE_FIREBASE_OAUTH_CLIENT_ID=156631080737-oehksn335gc8im1862k138nib87gtd9b.apps.googleusercontent.com'
      - '.'
      - '-f'
      - 'Dockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pantry-pal'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--allow-unauthenticated'

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'