steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=$_FIREBASE_API_KEY'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_FIRESTORE_DATABASE_ID=$_FIREBASE_FIRESTORE_DATABASE_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=$_FIREBASE_APP_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=$_FIREBASE_MEASUREMENT_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_OAUTH_CLIENT_ID=$_FIREBASE_OAUTH_CLIENT_ID'
      - '.'
      - '-f'
      - 'Dockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pantry-pal'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,VITE_FIREBASE_API_KEY=$_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID=$_FIREBASE_APP_ID'

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pantrypal/pantry-pal:$COMMIT_SHA'

substitutions:
  _FIREBASE_API_KEY: 'AIzaSyAO3xx6mnITcD9h6GDk7qhzpQMvSiswSVk'
  _FIREBASE_AUTH_DOMAIN: 'pantry-pal-66ed8.firebaseapp.com'
  _FIREBASE_PROJECT_ID: 'pantry-pal-66ed8'
  _FIREBASE_FIRESTORE_DATABASE_ID: 'default'
  _FIREBASE_STORAGE_BUCKET: 'pantry-pal-66ed8.firebasestorage.app'
  _FIREBASE_MESSAGING_SENDER_ID: '557285061653'
  _FIREBASE_APP_ID: '1:557285061653:web:d777e9405d61032bab8a1c'
  _FIREBASE_MEASUREMENT_ID: 'G-MM184JNZ75'
  _FIREBASE_OAUTH_CLIENT_ID: '156631080737-oehksn335gc8im1862k138nib87gtd9b.apps.googleusercontent.com'